[package]
name = "principal-check"
version = "0.1.0"
authors = ["Linwei Shang <linwei.shang@dfinity.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
